server {
		listen 3000;
		server_name juice-shop;

		location / {
			    proxy_pass http://juice:3000;
			    proxy_set_header Host $host;
		}
	
}

server {
		listen 3000;
		server_name dev.juice-shop;

		location / {
		    proxy_pass http://dev-page:80;
		    proxy_set_header Host $host;
		}

}
